apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: chkdags9k-python-gitops
  description: This is GitOps manifest for chkdags9k-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=chkdags9k-python
    backstage.io/kubernetes-id: chkdags9k-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: chkdags9k-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:chkdags9k-python
